# Use a Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY app /app

# Install dependencies
RUN pip install flask prometheus_client requests

# Expose Flask's default port
EXPOSE 5000

# Start the Flask app
CMD ["python", "main.py"]
